services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart : always
    environment:
      POSTGRES_DB: Aliatish_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: JwU52#%9JMu{
    ports: 
      - "5432:5432"
    volumes:
      - ./postres_data:/var/lib/postgressql/postres_data

  pageadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart:  always
    environment:
      PGADMIN_DEFAULT_EMAIL : alirezaatashnejad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: JwU52#%9JMu{
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lin/pgadmin
    depends_on:
      - postgres